import React, { useMemo, useState, useCallback, useEffect, useRef } from 'react';
import JSZip from 'jszip';
import type { FileEntry } from '../types';
import { generateProjectManifest } from '../services/geminiService';

type StackOption = 'react-vite';

interface BuilderProps {
  onClose: () => void;
  initialManifest?: FileEntry[] | null;
  initialProjectName?: string;
  initialDescription?: string;
}

const defaultProjectName = 'spark-project';

const ProjectBuilderModal: React.FC<BuilderProps> = ({ onClose, initialManifest, initialProjectName, initialDescription }) => {
  const [projectName, setProjectName] = useState<string>(initialProjectName ?? defaultProjectName);
  const [stack, setStack] = useState<StackOption>('react-vite');
  const [withNavbar, setWithNavbar] = useState(true);
  const [withFooter, setWithFooter] = useState(true);
  const [withContactForm, setWithContactForm] = useState(true);
  const [withAuthScreens, setWithAuthScreens] = useState(false);
  const [manifest, setManifest] = useState<FileEntry[] | null>(initialManifest ?? null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedPath, setSelectedPath] = useState<string | null>(null);
  const [modRequest, setModRequest] = useState<string>('');
  const [baseDescription, setBaseDescription] = useState<string>(initialDescription ?? '');
  const iframeRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    if (initialManifest) setManifest(initialManifest);
    if (initialProjectName) setProjectName(initialProjectName);
    if (initialDescription) setBaseDescription(initialDescription);
  }, [initialManifest, initialProjectName]);

  const createManifest = useCallback((): FileEntry[] => {
    const files: FileEntry[] = [];

    // README explaining how to use the generated UI package
    files.push({
      path: 'README.md',
      content: `# ${projectName}\n\nThis zip contains UI-only React components generated by Spark.\n\nHow to use:\n- Unzip anywhere.\n- Copy the \`src\` folder contents into your React project, or open as a new Vite React app.\n- Connect your own backend/database later.\n\nStack: React + Vite (UI only).\n`
    });

    // Basic Vite + React template files
    files.push({
      path: 'index.html',
      content: `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <link rel="icon" href="/vite.svg" />\n    <title>${projectName}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>`
    });

    files.push({
      path: 'tsconfig.json',
      content: `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true
  },
  "include": ["src"]
}`
    });

    files.push({
      path: 'src/main.tsx',
      content: `import React from 'react'\nimport { createRoot } from 'react-dom/client'\nimport App from './App'\nimport './index.css'\n\ncreateRoot(document.getElementById('root')!).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>\n)`
    });

    files.push({
      path: 'src/index.css',
      content: `:root {\n  --bg: #0b0b10;\n  --text: #e7e7ea;\n  --muted: #9aa0a6;\n  --accent: #10b981;\n}\nbody {\n  margin: 0;\n  font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;\n  background: var(--bg);\n  color: var(--text);\n}\nbutton {\n  cursor: pointer;\n}`
    });

    // Basic App with optional components
    let appImports = ["import React from 'react'", "import './index.css'"];
    let appBody = [`export default function App() {`, `  return (`, `    <div style={{ padding: 24 }}>`, `      <h1>${projectName}</h1>`];

    if (withNavbar) {
      appImports.push("import NavBar from './components/NavBar'");
      appBody.push('      <NavBar />');
      files.push({
        path: 'src/components/NavBar.tsx',
        content: `import React from 'react'\nexport default function NavBar() {\n  return (\n    <nav style={{display:'flex',gap:16,alignItems:'center',justifyContent:'space-between',padding:'12px 0'}}>\n      <div style={{fontWeight:700}}>Logo</div>\n      <div style={{display:'flex',gap:12}}>\n        <a href="#">Home</a>\n        <a href="#">Features</a>\n        <a href="#">Contact</a>\n      </div>\n    </nav>\n  )\n}`
      });
    }

    files.push({
      path: 'src/components/Hero.tsx',
      content: `import React from 'react'\nexport default function Hero() {\n  return (\n    <section style={{padding:'36px 0'}}>\n      <h2 style={{fontSize:28,margin:0}}>Build UIs fast with Spark</h2>\n      <p style={{color:'var(--muted)'}}>Pure frontend scaffolding. Connect your own backend later.</p>\n      <button style={{background:'var(--accent)',color:'#fff',border:'none',padding:'10px 16px',borderRadius:8}}>Get Started</button>\n    </section>\n  )\n}`
    });
    appImports.push("import Hero from './components/Hero'");
    appBody.push('      <Hero />');

    if (withContactForm) {
      appImports.push("import ContactForm from './components/ContactForm'");
      appBody.push('      <ContactForm />');
      files.push({
        path: 'src/components/ContactForm.tsx',
        content: `import React, { useState } from 'react'\nexport default function ContactForm() {\n  const [name,setName] = useState('');\n  const [email,setEmail] = useState('');\n  const [message,setMessage] = useState('');\n  const handleSubmit = (e: React.FormEvent) => {\n    e.preventDefault();\n    alert('This is UI-only. Connect your backend to handle submissions.');\n  }\n  return (\n    <form onSubmit={handleSubmit} style={{display:'grid',gap:12,maxWidth:480}}>\n      <input placeholder='Name' value={name} onChange={e=>setName(e.target.value)} />\n      <input placeholder='Email' value={email} onChange={e=>setEmail(e.target.value)} />\n      <textarea placeholder='Message' value={message} onChange={e=>setMessage(e.target.value)} />\n      <button type='submit' style={{background:'var(--accent)',color:'#fff',border:'none',padding:'10px 16px',borderRadius:8}}>Send</button>\n    </form>\n  )\n}`
      });
    }

    if (withAuthScreens) {
      files.push({
        path: 'src/pages/Login.tsx',
        content: `import React, { useState } from 'react'\nexport default function Login() {\n  const [email,setEmail] = useState('');\n  const [password,setPassword] = useState('');\n  const submit = (e: React.FormEvent)=>{e.preventDefault();alert('UI-only. Hook up auth later.')};\n  return (\n    <div style={{maxWidth:420}}>\n      <h2>Login</h2>\n      <form onSubmit={submit} style={{display:'grid',gap:12}}>\n        <input placeholder='Email' value={email} onChange={e=>setEmail(e.target.value)} />\n        <input type='password' placeholder='Password' value={password} onChange={e=>setPassword(e.target.value)} />\n        <button type='submit' style={{background:'var(--accent)',color:'#fff',border:'none',padding:'10px 16px',borderRadius:8}}>Login</button>\n      </form>\n    </div>\n  )\n}`
      });
      files.push({
        path: 'src/pages/Register.tsx',
        content: `import React, { useState } from 'react'\nexport default function Register() {\n  const [email,setEmail] = useState('');\n  const [password,setPassword] = useState('');\n  const submit = (e: React.FormEvent)=>{e.preventDefault();alert('UI-only. Hook up auth later.')};\n  return (\n    <div style={{maxWidth:420}}>\n      <h2>Register</h2>\n      <form onSubmit={submit} style={{display:'grid',gap:12}}>\n        <input placeholder='Email' value={email} onChange={e=>setEmail(e.target.value)} />\n        <input type='password' placeholder='Password' value={password} onChange={e=>setPassword(e.target.value)} />\n        <button type='submit' style={{background:'var(--accent)',color:'#fff',border:'none',padding:'10px 16px',borderRadius:8}}>Create account</button>\n      </form>\n    </div>\n  )\n}`
      });
      appImports.push("import Login from './pages/Login'", "import Register from './pages/Register'");
      appBody.push('      <div style={{display:"flex", gap:24}}><Login /><Register /></div>');
    }

    if (withFooter) {
      appImports.push("import Footer from './components/Footer'");
      appBody.push('      <Footer />');
      files.push({
        path: 'src/components/Footer.tsx',
        content: `import React from 'react'\nexport default function Footer(){\n  return (<footer style={{marginTop:48,padding:'24px 0',borderTop:'1px solid #1f2937',color:'var(--muted)'}}>\n    <small>&copy; ${new Date().getFullYear()} Spark UI</small>\n  </footer>)\n}`
      });
    }

    appBody.push('    </div>');
    appBody.push('  )');
    appBody.push('}');

    files.push({
      path: 'src/App.tsx',
      content: `${appImports.join('\n')}\n\n${appBody.join('\n')}\n`
    });

    // Minimal package.json for the generated project (optional)
    files.push({
      path: 'package.json',
      content: `{
  "name": "${projectName}",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.2.0",
    "react-dom": "^19.2.0"
  },
  "devDependencies": {
    "vite": "^6.2.0",
    "@vitejs/plugin-react": "^5.0.0",
    "typescript": "~5.8.2"
  }
}`
    });

    // Include the vite.svg favicon
    files.push({
      path: 'public/vite.svg',
      content: `<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 32 32\"><circle cx=\"16\" cy=\"16\" r=\"16\" fill=\"#10b981\"/><text x=\"50%\" y=\"55%\" dominant-baseline=\"middle\" text-anchor=\"middle\" font-size=\"14\" fill=\"#fff\">V</text></svg>`
    });

    return files;
  }, [projectName, withNavbar, withFooter, withContactForm, withAuthScreens]);

  const handleGenerate = async () => {
    try {
      setIsGenerating(true);
      setError(null);
      // For now, generation is local (Option A). Later we can swap to serverless.
      const files = createManifest();
      setManifest(files);
    } catch (e: any) {
      setError(e?.message ?? 'تعذر إنشاء الملفات');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleRegenerateWithRequest = async () => {
    try {
      setIsGenerating(true);
      setError(null);
      const description = `${baseDescription}\n\nالتعديلات المطلوبة:\n${modRequest}`.trim();
      const files = await generateProjectManifest(description);
      setManifest(files);
      setModRequest('');
    } catch (e: any) {
      setError(e?.message ?? 'تعذر تطبيق التعديلات');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadZip = async () => {
    try {
      const files = manifest ?? createManifest();
      const zip = new JSZip();
      files.forEach(f => {
        zip.file(f.path, f.content);
      });
      const blob = await zip.generateAsync({ type: 'blob' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${projectName}.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e: any) {
      setError(e?.message ?? 'فشل تنزيل الملف المضغوط');
    }
  };

  const previewUrl = useMemo(() => {
    if (!manifest) return null;
    const previewFile = manifest.find(f => f.path.toLowerCase() === 'preview.html');
    if (!previewFile) return null;
    const blob = new Blob([previewFile.content], { type: 'text/html' });
    return URL.createObjectURL(blob);
  }, [manifest]);

  useEffect(() => {
    return () => {
      // Cleanup blob URL when modal unmounts
      if (previewUrl) URL.revokeObjectURL(previewUrl);
    };
  }, [previewUrl]);

  return (
    <div className="fixed inset-0 z-40 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/60" onClick={onClose} />
      <div className="relative bg-zinc-100 dark:bg-zinc-900 text-zinc-900 dark:text-zinc-100 rounded-xl p-4 sm:p-6 w-[95%] sm:w-[720px] shadow-lg border border-zinc-300/50 dark:border-zinc-800/50">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-bold">منشئ المشاريع (UI فقط)</h2>
          <button onClick={onClose} className="px-3 py-1 rounded-md bg-zinc-200 dark:bg-zinc-800">إغلاق</button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label className="text-sm">اسم المشروع</label>
            <input
              className="w-full mt-1 p-2 rounded-md bg-zinc-50 dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-700"
              value={projectName}
              onChange={(e) => setProjectName(e.target.value)}
              placeholder="spark-project"
            />

            <div className="mt-4">
              <label className="text-sm">التكديس التقني</label>
              <select
                className="w-full mt-1 p-2 rounded-md bg-zinc-50 dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-700"
                value={stack}
                onChange={(e) => setStack(e.target.value as StackOption)}
              >
                <option value="react-vite">React + Vite (مقترح للأحجام الصغيرة)</option>
              </select>
            </div>
          </div>

          <div>
            <div className="font-semibold mb-2">الواجهات المطلوبة</div>
            <div className="space-y-2">
              <label className="flex items-center gap-2">
                <input type="checkbox" checked={withNavbar} onChange={(e)=>setWithNavbar(e.target.checked)} />
                شريط علوي (Navbar)
              </label>
              <label className="flex items-center gap-2">
                <input type="checkbox" checked={withFooter} onChange={(e)=>setWithFooter(e.target.checked)} />
                ذيل الصفحة (Footer)
              </label>
              <label className="flex items-center gap-2">
                <input type="checkbox" checked={withContactForm} onChange={(e)=>setWithContactForm(e.target.checked)} />
                نموذج تواصل
              </label>
              <label className="flex items-center gap-2">
                <input type="checkbox" checked={withAuthScreens} onChange={(e)=>setWithAuthScreens(e.target.checked)} />
                شاشات تسجيل الدخول/التسجيل (UI فقط)
              </label>
            </div>
          </div>
        </div>

        {/* Editor and Preview */}
        <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="border border-zinc-300 dark:border-zinc-800 rounded-md overflow-hidden">
            <div className="px-3 py-2 text-sm bg-zinc-200 dark:bg-zinc-800 flex items-center justify-between">
              <span>الملفات</span>
              {selectedPath && (
                <button
                  className="text-xs px-2 py-1 rounded bg-emerald-600 text-white"
                  onClick={() => setSelectedPath(null)}
                >
                  إغلاق المحرر
                </button>
              )}
            </div>
            <div className="max-h-48 overflow-auto p-2 text-xs">
              {manifest?.map(f => (
                <div key={f.path} className="flex items-center justify-between py-1">
                  <button className="underline" onClick={() => setSelectedPath(f.path)}>{f.path}</button>
                  <button
                    className="px-2 py-1 text-[11px] rounded bg-zinc-200 dark:bg-zinc-800"
                    onClick={() => {
                      const blob = new Blob([f.content], { type: 'text/plain' });
                      const url = URL.createObjectURL(blob);
                      const a = document.createElement('a');
                      a.href = url;
                      a.download = f.path.split('/').pop() || 'file.txt';
                      a.click();
                      URL.revokeObjectURL(url);
                    }}
                  >
                    تنزيل
                  </button>
                </div>
              ))}
            </div>
            {selectedPath && (
              <div className="border-t border-zinc-300 dark:border-zinc-800">
                <div className="px-3 py-2 text-xs bg-zinc-100 dark:bg-zinc-900">تحرير: {selectedPath}</div>
                <textarea
                  className="w-full h-40 p-2 text-xs bg-zinc-50 dark:bg-zinc-900 border-0 outline-none"
                  value={manifest?.find(m => m.path === selectedPath)?.content ?? ''}
                  onChange={(e) => {
                    const val = e.target.value;
                    setManifest(prev => prev?.map(m => m.path === selectedPath ? { ...m, content: val } : m) ?? null);
                  }}
                />
              </div>
            )}
          </div>

          <div className="border border-zinc-300 dark:border-zinc-800 rounded-md overflow-hidden">
            <div className="px-3 py-2 text-sm bg-zinc-200 dark:bg-zinc-800 flex items-center justify-between">
              <span>المعاينة الحية</span>
              {previewUrl ? (
                <a className="text-xs underline" href={previewUrl} target="_blank" rel="noreferrer">فتح في نافذة جديدة</a>
              ) : (
                <span className="text-xs">لا يوجد preview.html</span>
              )}
            </div>
            <div className="h-64 bg-white dark:bg-zinc-950">
              {previewUrl ? (
                <iframe ref={iframeRef} src={previewUrl} className="w-full h-full" />
              ) : (
                <div className="p-4 text-xs text-zinc-600 dark:text-zinc-400">أضف ملف preview.html ذاتي الاكتفاء لتمكين المعاينة.</div>
              )}
            </div>
          </div>
        </div>

        {error && (
          <div className="mt-4 text-red-500 text-sm">{error}</div>
        )}

        <div className="mt-6 flex flex-wrap gap-3">
          {!manifest && (
            <button
              disabled={isGenerating}
              onClick={handleGenerate}
              className="px-4 py-2 rounded-lg bg-emerald-600 text-white hover:bg-emerald-700 disabled:opacity-60"
            >
              {isGenerating ? 'جاري الإنشاء...' : 'إنشاء الملفات'}
            </button>
          )}
          <button
            onClick={handleDownloadZip}
            className="px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-700"
          >
            تنزيل كملف ZIP
          </button>
          <div className="flex-1" />
          <input
            placeholder="اكتب طلب التعديلات (مثال: لون داكن، زر أكبر، إضافة قسم ميزات)"
            className="flex-1 min-w-48 p-2 rounded-md bg-zinc-50 dark:bg-zinc-800 border border-zinc-300 dark:border-zinc-700"
            value={modRequest}
            onChange={(e) => setModRequest(e.target.value)}
          />
          <button
            disabled={isGenerating || !modRequest.trim()}
            onClick={handleRegenerateWithRequest}
            className="px-4 py-2 rounded-lg bg-purple-600 text-white hover:bg-purple-700 disabled:opacity-60"
          >
            تطبيق طلب التعديل
          </button>
        </div>

        {manifest && (
          <div className="mt-6 max-h-48 overflow-auto border border-zinc-300 dark:border-zinc-800 rounded-md p-2 text-xs">
            {manifest.map((f) => (
              <div key={f.path} className="flex items-center justify-between py-1">
                <span>{f.path}</span>
                <button
                  className="px-2 py-1 text-[11px] rounded bg-zinc-200 dark:bg-zinc-800"
                  onClick={() => {
                    const blob = new Blob([f.content], { type: 'text/plain' });
                    const url = URL.createObjectURL(blob);
                    const a = document.createElement('a');
                    a.href = url;
                    a.download = f.path.split('/').pop() || 'file.txt';
                    a.click();
                    URL.revokeObjectURL(url);
                  }}
                >
                  تنزيل هذا الملف
                </button>
              </div>
            ))}
          </div>
        )}

        <div className="mt-4 text-[12px] text-zinc-500 dark:text-zinc-400">
          {manifest
            ? 'تم إنشاء الحزمة تلقائيًا بناءً على وصفك. يمكنك مراجعتها، تعديلها يدويًا، أو طلب تعديلات وإعادة الإنشاء، ثم تنزيلها.'
            : 'ملاحظة: الإنشاء يتم داخل المتصفح (خيار مناسب لمشاريع صغيرة). للمشاريع الكبيرة أو لحماية مفاتيح API يمكننا لاحقًا نقل العملية إلى دالة Serverless على Vercel.'}
        </div>
      </div>
    </div>
  );
};

export default ProjectBuilderModal;